# Generated by Django 4.2.10 on 2024-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(default="0T1CZWVB", max_length=8, unique=True),
        ),
    ]
