# Generated by Django 4.2.10 on 2024-03-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0002_alter_wallet_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walletuser",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(default="4BEIAV94", max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="walletuser",
            name="id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
