# Generated by Django 4.2.10 on 2024-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_remove_walletuser_user_id_alter_wallet_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(default="50W1IEL5", max_length=8, unique=True),
        ),
    ]
