# Generated by Django 4.2.10 on 2024-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_rename_transfer_amount_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.TextField(),
        ),
    ]
